CREATE TABLE IF NOT EXISTS Products(
      ID INT NOT NULL UNIQUE AUTO_INCREMENT,
      Name VARCHAR(255) NOT NULL,
      info VARCHAR(255),
      Price DECIMAL(10,2) NOT NULL,
      PRIMARY KEY  (ID)
)